version: '3.7'
services:
    web:
        build:
            context: .
            dockerfile: ./dockerfiles/web_dockerfile
        ports:
            - 5000:5000
        # container_name: blog_container
        environment:
          - FLASK_APP=blog.py
          - FLASK_ENV=production
          - BLOG_ADMIN_EMAIL=admin@admin.com
          - BLOG_ADMIN_USERNAME=admin
          - BLOG_ADMIN_NAME=admin
          - BLOG_ADMIN_PASSWORD=admin
          - DATABASE_PASSWORD=root
          - REDIS_URI:redis://redis_password@redis:6379
        volumes:
            - ./:/usr/src/app/
            # - type: volume 
            #   source: source_vol
            #   target: /usr/src/app
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
    db:
        image: mariadb
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=blog
        volumes:
            - type: volume 
              source: db_data_vol
              target: /var/lib/mysql/
    redis:
        build:
          context: .
          dockerfile: ./dockerfiles/redis_dockerfile
        ports:
            - 6379:6379
        volumes:
           - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
           - type: volume
             source: redis_data_vol
             target: /var/lib/redis/

    nginx:
        build:
            context: .
            dockerfile: ./dockerfiles/nginx_dockerfile
            args:
                - http2=yes
        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./app/static:/usr/src/app/static/
            - /etc/letsencrypt:/etc/letsencrypt:ro
            # - ./logs/:/var/logs/
        ports:
            - 443:443
            - 80:80
        links:
            - web
volumes:
    # source_vol:
    #     external: true
    db_data_vol:
    redis_data_vol:
